title: Ram Ravi
theme: jekyll-theme-minimal

description: >
  <p>
    <img src="/assets/git-profile-pic.JPG"
         width="150"
         style="border-radius:50%; margin-bottom:10px;" />
  </p>
  <p>
    <a href="https://www.linkedin.com/in/ramgopal-ravi-58179771">LinkedIn</a> ·
    <a href="https://scholar.google.com/citations?user=-08NfRgAAAAJ">Scholar</a> ·
    <a href="mailto:raviramgopal@gmail.com">Email</a> ·
    <a href="/assets/Ram_Ravi_Resume_v3.pdf">Resume</a>
  </p>
