title: Ram Ravi
theme: jekyll-theme-minimal

description: >
  <p>
    <img src="/assets/git-profile-pic.JPG"
         width="150"
         style="border-radius:50%; margin-bottom:10px;" />
  </p>
  <p>
    <a href="https://github.com/ramravi2403">GitHub</a> ·
    <a href="https://scholar.google.com/citations?user=YOUR_ID">Scholar</a> ·
    <a href="mailto:raviramgopal@gmail.com">Email</a> ·
    <a href="/assets/Ram%20Ravi%20-%20Resume%20(AIML).pdf">Resume</a>
  </p>
